function escapeHtml(value) {
	return String(value)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/\"/g, '&quot;')
		.replace(/'/g, '&#039;')
}

function findFile(files, path) {
	return files.find((file) => file.path === path)?.content || ''
}

function extractHeadline(source, fallback) {
	const match = source.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)
	if (!match) return fallback
	return match[1].replace(/\{[^}]*\}/g, '').replace(/<[^>]*>/g, '').trim() || fallback
}

function extractSubline(source, fallback) {
	const match = source.match(/<p[^>]*>([\s\S]*?)<\/p>/i)
	if (!match) return fallback
	return match[1].replace(/\{[^}]*\}/g, '').replace(/<[^>]*>/g, '').trim() || fallback
}

function extractProductNames(source) {
	const names = []
	const regex = /name:\s*'([^']+)'/g
	let match = regex.exec(source)

	while (match) {
		names.push(match[1])
		match = regex.exec(source)
	}

	return names.slice(0, 6)
}

export function buildPreviewHtml(files, projectName = 'Generated Website') {
	if (!Array.isArray(files) || files.length === 0) {
		return '<!doctype html><html><body><p style="font-family:system-ui;padding:16px;">No generated files to preview yet.</p></body></html>'
	}

	const navbar = findFile(files, 'components/Navbar.jsx')
	const hero = findFile(files, 'components/Hero.jsx')
	const productList = findFile(files, 'components/ProductList.jsx')
	const footer = findFile(files, 'components/Footer.jsx')

	const heroTitle = escapeHtml(extractHeadline(hero, 'Your generated hero headline appears here.'))
	const heroSubtitle = escapeHtml(extractSubline(hero, 'Preview uses a safe renderer based on generated component files.'))
	const products = extractProductNames(productList)

	const productCards = products.length
		? products.map((name) => `<article class="card"><div class="media"></div><h3>${escapeHtml(name)}</h3><p>$99</p></article>`).join('')
		: '<article class="card"><div class="media"></div><h3>Generated product</h3><p>$99</p></article>'

	const navLabel = escapeHtml(extractSubline(navbar, projectName))
	const footerText = escapeHtml(extractSubline(footer, 'Generated by Nexora Studio'))

	return `<!doctype html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<style>
			* { box-sizing: border-box; }
			body { margin: 0; font-family: ui-sans-serif, system-ui; background: #f8fafc; color: #0f172a; }
			.wrap { max-width: 1120px; margin: 0 auto; padding: 0 20px; }
			.nav { border-bottom: 1px solid #e2e8f0; background: #ffffff; }
			.nav .wrap { display: flex; justify-content: space-between; align-items: center; padding-top: 16px; padding-bottom: 16px; }
			.brand { font-weight: 800; }
			.hero { padding: 64px 0 40px; }
			.hero-box { border: 1px solid #e2e8f0; background: white; border-radius: 20px; padding: 32px; }
			.hero h1 { margin: 0; font-size: clamp(28px, 5vw, 48px); line-height: 1.1; }
			.hero p { margin-top: 16px; color: #475569; line-height: 1.6; }
			.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); margin-top: 24px; }
			.card { border: 1px solid #e2e8f0; background: #fff; border-radius: 16px; padding: 14px; }
			.card h3 { margin: 10px 0 6px; font-size: 16px; }
			.card p { margin: 0; font-size: 14px; color: #64748b; }
			.media { height: 120px; border-radius: 12px; background: linear-gradient(135deg, #e2e8f0, #f1f5f9); }
			.footer { margin-top: 40px; border-top: 1px solid #e2e8f0; background: #fff; }
			.footer .wrap { padding-top: 20px; padding-bottom: 20px; color: #64748b; font-size: 14px; }
		</style>
	</head>
	<body>
		<header class="nav">
			<div class="wrap">
				<strong class="brand">${escapeHtml(projectName)}</strong>
				<span>${navLabel}</span>
			</div>
		</header>

		<section class="hero">
			<div class="wrap">
				<div class="hero-box">
					<h1>${heroTitle}</h1>
					<p>${heroSubtitle}</p>

					<div class="grid">${productCards}</div>
				</div>
			</div>
		</section>

		<footer class="footer">
			<div class="wrap">${footerText}</div>
		</footer>
	</body>
</html>`
}
function escapeHtml(value) {
	return String(value)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/\"/g, '&quot;')
		.replace(/'/g, '&#039;')
}

function findFile(files, path) {
	return files.find((file) => file.path === path)?.content || ''
}

function extractHeadline(source, fallback) {
	const match = source.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)
	if (!match) return fallback
	return match[1].replace(/\{[^}]*\}/g, '').replace(/<[^>]*>/g, '').trim() || fallback
}

function extractSubline(source, fallback) {
	const match = source.match(/<p[^>]*>([\s\S]*?)<\/p>/i)
	if (!match) return fallback
	return match[1].replace(/\{[^}]*\}/g, '').replace(/<[^>]*>/g, '').trim() || fallback
}

function extractProductNames(source) {
	const names = []
	const regex = /name:\s*'([^']+)'/g
	let match = regex.exec(source)

	while (match) {
		names.push(match[1])
		match = regex.exec(source)
	}

	return names.slice(0, 6)
}

export function buildPreviewHtml(files, projectName = 'Generated Website') {
	if (!Array.isArray(files) || files.length === 0) {
		return '<!doctype html><html><body><p style="font-family:system-ui;padding:16px;">No generated files to preview yet.</p></body></html>'
	}

	const navbar = findFile(files, 'components/Navbar.jsx')
	const hero = findFile(files, 'components/Hero.jsx')
	const productList = findFile(files, 'components/ProductList.jsx')
	const footer = findFile(files, 'components/Footer.jsx')

	const heroTitle = escapeHtml(extractHeadline(hero, 'Your generated hero headline appears here.'))
	const heroSubtitle = escapeHtml(extractSubline(hero, 'Preview uses a safe renderer based on generated component files.'))
	const products = extractProductNames(productList)

	const productCards = products.length
		? products.map((name) => `<article class="card"><div class="media"></div><h3>${escapeHtml(name)}</h3><p>$99</p></article>`).join('')
		: '<article class="card"><div class="media"></div><h3>Generated product</h3><p>$99</p></article>'

	const navLabel = escapeHtml(extractSubline(navbar, projectName))
	const footerText = escapeHtml(extractSubline(footer, 'Generated by Nexora Studio'))

	return `<!doctype html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<style>
			* { box-sizing: border-box; }
			body { margin: 0; font-family: ui-sans-serif, system-ui; background: #f8fafc; color: #0f172a; }
			.wrap { max-width: 1120px; margin: 0 auto; padding: 0 20px; }
			.nav { border-bottom: 1px solid #e2e8f0; background: #ffffff; }
			.nav .wrap { display: flex; justify-content: space-between; align-items: center; padding-top: 16px; padding-bottom: 16px; }
			.brand { font-weight: 800; }
			.hero { padding: 64px 0 40px; }
			.hero-box { border: 1px solid #e2e8f0; background: white; border-radius: 20px; padding: 32px; }
			.hero h1 { margin: 0; font-size: clamp(28px, 5vw, 48px); line-height: 1.1; }
			.hero p { margin-top: 16px; color: #475569; line-height: 1.6; }
			.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); margin-top: 24px; }
			.card { border: 1px solid #e2e8f0; background: #fff; border-radius: 16px; padding: 14px; }
			.card h3 { margin: 10px 0 6px; font-size: 16px; }
			.card p { margin: 0; font-size: 14px; color: #64748b; }
			.media { height: 120px; border-radius: 12px; background: linear-gradient(135deg, #e2e8f0, #f1f5f9); }
			.footer { margin-top: 40px; border-top: 1px solid #e2e8f0; background: #fff; }
			.footer .wrap { padding-top: 20px; padding-bottom: 20px; color: #64748b; font-size: 14px; }
		</style>
	</head>
	<body>
		<header class="nav">
			<div class="wrap">
				<strong class="brand">${escapeHtml(projectName)}</strong>
				<span>${navLabel}</span>
			</div>
		</header>

		<section class="hero">
			<div class="wrap">
				<div class="hero-box">
					<h1>${heroTitle}</h1>
					<p>${heroSubtitle}</p>

					<div class="grid">${productCards}</div>
				</div>
			</div>
		</section>

		<footer class="footer">
			<div class="wrap">${footerText}</div>
		</footer>
	</body>
</html>`
}
